# will inherit from .aws and/or .hosttech
version: "3.8"

services:
  postgres:
    container_name: "${POSTGRES_HOST}"
    image: postgres:15
    user: postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    expose:
      - "${POSTGRES_PORT}"
    logging:
      driver: "json-file"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER} || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
    env_file: .env
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data:z

volumes:
  postgres:
